### ISSUE TITLE
No gradients provided for any variable

### ISSUE THREAD

**Issue by nikitalokhmachev-ai** [tonouchi510/simclr-tf2-distribute#1]
Hello! Thanks for sharing your implementation of SimCLR! The code is much easier to read, which allows me to reuse it for my own purposes pretty quickly and easily. 
However, I faced a problem when trying to pretrain SimCLR model in my setting. I changed some of your code to get data from my local storage. Also, I am using 4 GPU's instead of a TPU. I did not change the code in the training step. 
When I try to train the model, I get the following error:
`ValueError: No gradients provided for any variable: ['conv1_conv/kernel:0', 'conv1_conv/bias:0', 'conv1_bn/gamma:0', 'conv1_bn/beta:0', 'conv2_block1_1_conv/kernel:0', 'conv2_block1_1_conv/bias:0', ...`.

I googled similar issues but could not find any solutions that would help me.

Here's the colab notebook to reproduce the error. Just run it!
https://colab.research.google.com/drive/1HnGZkS2dIhfIVHkh9dtAnQeAQ5aDwx-d?usp=sharing

Do you know what the problem could be?
Any response would be appreciated. Thanks in advance!

**Comment by tonouchi510** [comment]
Thank you for your feedback! 

I also encountered the same problem, but haven't found a solution yet.

I had written some code that works with MirroredStrategy a long time ago, so I put it in the "mirrored-strategy" directory for the time being.
However, there may be a bug in code.

**Comment by nikitalokhmachev-ai** [comment]
Thanks for the answer!
I'll have a look at the code for MirroredStrategy then.
